version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9001:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/props.yml
